//
// CharactersList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CharactersList: Codable, JSONEncodable, Hashable {

    public var docs: [CharacterModel]
    public var total: Int
    public var limit: Int
    public var offset: Int?
    public var page: Int?
    public var pages: Int?

    public init(docs: [CharacterModel], total: Int, limit: Int, offset: Int? = nil, page: Int? = nil, pages: Int? = nil) {
        self.docs = docs
        self.total = total
        self.limit = limit
        self.offset = offset
        self.page = page
        self.pages = pages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docs
        case total
        case limit
        case offset
        case page
        case pages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(docs, forKey: .docs)
        try container.encode(total, forKey: .total)
        try container.encode(limit, forKey: .limit)
        try container.encodeIfPresent(offset, forKey: .offset)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(pages, forKey: .pages)
    }
}

