//
// QuoteModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QuoteModel: Codable, JSONEncodable, Hashable {

    public var id: String
    public var dialog: String
    public var movie: String
    public var character: String

    public init(id: String, dialog: String, movie: String, character: String) {
        self.id = id
        self.dialog = dialog
        self.movie = movie
        self.character = character
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case dialog
        case movie
        case character
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(dialog, forKey: .dialog)
        try container.encode(movie, forKey: .movie)
        try container.encode(character, forKey: .character)
    }
}

