//
// QuotesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class QuotesAPI {

    /**
     List of all movie quotes
     
     - parameter limit: (query) Pagination limit (optional)
     - parameter page: (query) Pagination page (optional)
     - returns: QuotesList
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func quotesGet(limit: Int? = nil, page: Int? = nil) async throws -> QuotesList {
        return try await quotesGetWithRequestBuilder(limit: limit, page: page).execute().body
    }

    /**
     List of all movie quotes
     - GET /quote/
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter limit: (query) Pagination limit (optional)
     - parameter page: (query) Pagination page (optional)
     - returns: RequestBuilder<QuotesList> 
     */
    open class func quotesGetWithRequestBuilder(limit: Int? = nil, page: Int? = nil) -> RequestBuilder<QuotesList> {
        let localVariablePath = "/quote/"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<QuotesList>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
